# Generated by Django 2.2 on 2019-04-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roommodel',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='roommodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
